# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622a5f52a6425bee476b0750ad631cf65b293b7ce5a13ad6844c7c4a7516ec4bdfb57f4f06365f59e389de79879b2dbf768dd7fe53d84fdce09ee342961371e4

test:
  secret_key_base: 2c41394402a1ad59533f1d844ee0d686d587a4ebd06ff004835f278d4ebd5e9365a7d26e8b518f16952cc13e65ae635630a4016bdd6c5ec9df2351277c8d11f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
